### ISSUE TITLE
Package conventions/"Company" name?

### ISSUE THREAD

**Issue by BrianLeblanc98** [EthanHalliday/JavaChessProject#5]
How do you feel about following package conventions? It isn't super important for us to use full naming conventions, but I think it would be good to get used to them. If we do end up using them, we will have to come up with a "Company" name, since the standard package scheme is something like: "com.sun.java.accessibility", so ours would have to look like "com.%website/company%.JavaChessProject"

**Comment by EthanHalliday** [comment]
That sounds good to me. I have no real preference when it comes to such things, as long as we set a standard. As for a name, we can figure something out.

**Comment by BrianLeblanc98** [comment]
Alright, we'll figure out a name at some point when we all meet up
